/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RESOURCEMANAGER_H_RPCGEN
#define _RESOURCEMANAGER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Request_user_authentication {
	char *userId;
	char *action;
	char *resource;
};
typedef struct Request_user_authentication Request_user_authentication;

struct Response_authentication {
	char *authToken;
};
typedef struct Response_authentication Response_authentication;

struct Request_user_access {
	char *userId;
	char *authToken;
	char *refreshToken;
	int mode;
};
typedef struct Request_user_access Request_user_access;

struct Response_user_access {
	char *accessToken;
	char *refreshToken;
	char *message;
	int opNumber;
};
typedef struct Response_user_access Response_user_access;

struct Request_user_validate {
	char *action;
	char *resource;
	char *accessToken;
};
typedef struct Request_user_validate Request_user_validate;

struct Response_user_validate {
	char *info;
};
typedef struct Response_user_validate Response_user_validate;

#define RESOURCE_MANAGER 0x2fffffff
#define RESOURCE_MANAGER_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define USER_AUTH 1
extern  Response_authentication * user_auth_1(Request_user_authentication *, CLIENT *);
extern  Response_authentication * user_auth_1_svc(Request_user_authentication *, struct svc_req *);
#define USER_ACC 2
extern  Response_user_access * user_acc_1(Request_user_access *, CLIENT *);
extern  Response_user_access * user_acc_1_svc(Request_user_access *, struct svc_req *);
#define USER_VALIDATE 3
extern  Response_user_validate * user_validate_1(Request_user_validate *, CLIENT *);
extern  Response_user_validate * user_validate_1_svc(Request_user_validate *, struct svc_req *);
extern int resource_manager_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define USER_AUTH 1
extern  Response_authentication * user_auth_1();
extern  Response_authentication * user_auth_1_svc();
#define USER_ACC 2
extern  Response_user_access * user_acc_1();
extern  Response_user_access * user_acc_1_svc();
#define USER_VALIDATE 3
extern  Response_user_validate * user_validate_1();
extern  Response_user_validate * user_validate_1_svc();
extern int resource_manager_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Request_user_authentication (XDR *, Request_user_authentication*);
extern  bool_t xdr_Response_authentication (XDR *, Response_authentication*);
extern  bool_t xdr_Request_user_access (XDR *, Request_user_access*);
extern  bool_t xdr_Response_user_access (XDR *, Response_user_access*);
extern  bool_t xdr_Request_user_validate (XDR *, Request_user_validate*);
extern  bool_t xdr_Response_user_validate (XDR *, Response_user_validate*);

#else /* K&R C */
extern bool_t xdr_Request_user_authentication ();
extern bool_t xdr_Response_authentication ();
extern bool_t xdr_Request_user_access ();
extern bool_t xdr_Response_user_access ();
extern bool_t xdr_Request_user_validate ();
extern bool_t xdr_Response_user_validate ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RESOURCEMANAGER_H_RPCGEN */
