/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "resourcemanager.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Request *
response_1(argp, clnt)
	Request *argp;
	CLIENT *clnt;
{
	static Request clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, RESPONSE, xdr_Request, argp, xdr_Request, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
