/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "resourcemanager.h"

bool_t
xdr_Request(xdrs, objp)
	XDR *xdrs;
	Request *objp;
{

	if (!xdr_string(xdrs, &objp->user_id, 15))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->action, 20))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->resource, 20))
		return (FALSE);
	return (TRUE);
}
