/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RESOURCEMANAGER_H_RPCGEN
#define _RESOURCEMANAGER_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct Request {
	char *user_id;
	char *action;
	char *resource;
};
typedef struct Request Request;
#ifdef __cplusplus
extern "C" bool_t xdr_Request(XDR *, Request*);
#elif __STDC__
extern  bool_t xdr_Request(XDR *, Request*);
#else /* Old Style C */
bool_t xdr_Request();
#endif /* Old Style C */


#define RESOURCE_MANAGER ((rpc_uint)0x2fffffff)
#define RESOURCE_MANAGER_VERSION ((rpc_uint)1)

#ifdef __cplusplus
#define RESPONSE ((rpc_uint)1)
extern "C" Request * response_1(Request *, CLIENT *);
extern "C" Request * response_1_svc(Request *, struct svc_req *);

#elif __STDC__
#define RESPONSE ((rpc_uint)1)
extern  Request * response_1(Request *, CLIENT *);
extern  Request * response_1_svc(Request *, struct svc_req *);

#else /* Old Style C */
#define RESPONSE ((rpc_uint)1)
extern  Request * response_1();
extern  Request * response_1_svc();
#endif /* Old Style C */

#endif /* !_RESOURCEMANAGER_H_RPCGEN */
